<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 macbook_2023.gltf --transform
Author: akshatmittal (https://sketchfab.com/akshatmittal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-macbook-air-15-space-gray-2023-e8d82e341c794141a2561c2c9d01d79e
Title: Apple Macbook Air 15 (Space Gray) 2023
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/macbook_2023-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.01}>
      <T.Mesh geometry={gltf.nodes.xVreGKoBGSZYMij.geometry} material={gltf.materials.dKLyhhkbEyMrqky} />
      <T.Mesh geometry={gltf.nodes.CTBERffHyoCSDBm_0.geometry} material={gltf.materials.YjmXmicdBWsFQyD} />
      <T.Mesh geometry={gltf.nodes.hczGzWOWpedUDYd_0.geometry} material={gltf.materials.pEUnNAGXCoAFoUk} />
      <T.Mesh geometry={gltf.nodes.biHEvGDNnTqamRb.geometry} material={gltf.materials.dFfswgailNMtaYj} />
      <T.Mesh geometry={gltf.nodes.TyOrApjEOLhYCaF.geometry} material={gltf.materials.AZirwHJdxxcChtp} />
      <T.Mesh geometry={gltf.nodes.vrIckaCELZpnnNK.geometry} material={gltf.materials.dkOmcmuFedorUKC} />
      <T.Mesh geometry={gltf.nodes.SadnAkehSlxIwKv.geometry} material={gltf.materials.VNZklasZKSWjWUk} />
      <T.Mesh geometry={gltf.nodes.OrhpMXCxeprcNok.geometry} material={gltf.materials.OfvrpEsWzbOpbcs} />
      <T.Mesh geometry={gltf.nodes.aLWGnOLpsFWVSfy.geometry} material={gltf.materials.iFCKstMLETFqCmZ} />
      <T.Mesh geometry={gltf.nodes.WDUVUVPpNjdIPkb.geometry} material={gltf.materials.ZPlxrBOYjSNYvVB} />
      <T.Mesh geometry={gltf.nodes.NqUinIWcwSlXpvt.geometry} material={gltf.materials.rvYnnyqXrbFJXxh} />
      <T.Mesh geometry={gltf.nodes.MaufYfIBnxcfRgH.geometry} material={gltf.materials.SsSIPrCyVNTOxvd} />
      <T.Mesh geometry={gltf.nodes.aIqeGXayDxWnOWQ.geometry} material={gltf.materials.dkOmcmuFedorUKC} />
      <T.Mesh geometry={gltf.nodes.HrtjMXqDCcINmDE_0.geometry} material={gltf.materials.BfIgIOaUEgyoEft} />
      <T.Mesh geometry={gltf.nodes.zWqVyCKpTAuZNiu_0.geometry} material={gltf.materials.zFJMMvikHFjtmzd} />
      <T.Mesh geometry={gltf.nodes.MYVKQTLmUkzzlBj_0.geometry} material={gltf.materials.jIhmcgKbjDOICsY} />
      <T.Mesh geometry={gltf.nodes.qEJjkxdFZFWJWzR_0.geometry} material={gltf.materials.JKvAHnqjqlqshmY} />
      <T.Mesh geometry={gltf.nodes.lvlCIzdfTmsrnsM.geometry} material={gltf.materials.iFCKstMLETFqCmZ} />
      <T.Mesh geometry={gltf.nodes.eeWSraIVipLsSmX_0.geometry} material={gltf.materials.JKvAHnqjqlqshmY} />
      <T.Mesh geometry={gltf.nodes.PgbYkhvRdcmMeGL.geometry} material={gltf.materials.wOIDWopwzKBeTNU} />
      <T.Mesh geometry={gltf.nodes.rktWdhtZkCSmqne.geometry} material={gltf.materials.ZrrjpMZNDbttBCc} />
      <T.Mesh geometry={gltf.nodes.hztTkkTJBJTZDmk.geometry} material={gltf.materials.ZrrjpMZNDbttBCc} />
      <T.Mesh geometry={gltf.nodes.bHBjPHbrqJmhyoR.geometry} material={gltf.materials.ZrrjpMZNDbttBCc} />
      <T.Mesh geometry={gltf.nodes.HHcJitDCPTdgnFk.geometry} material={gltf.materials.RMDHOHZakhhXXHT} />
      <T.Mesh geometry={gltf.nodes.DRGkWmkJlgmNDJU.geometry} material={gltf.materials.RMDHOHZakhhXXHT} />
      <T.Mesh geometry={gltf.nodes.KMwpdMtieDqmHVU.geometry} material={gltf.materials.RMDHOHZakhhXXHT} />
      <T.Mesh geometry={gltf.nodes.KgPDMIRPrxAynTV.geometry} material={gltf.materials.hZBlDyddxAQhuPm} />
      <T.Mesh geometry={gltf.nodes.XwGJfoaIrduFPcU.geometry} material={gltf.materials.YjmXmicdBWsFQyD} />
      <T.Mesh geometry={gltf.nodes.ACMWKGtOCqXifQY.geometry} material={gltf.materials.RMDHOHZakhhXXHT} />
      <T.Mesh geometry={gltf.nodes.BkHyotPbPWzwAAj.geometry} material={gltf.materials.sRPrqogRtliLLae} />
      <T.Mesh geometry={gltf.nodes.bkcxDtALZjuqGGQ.geometry} material={gltf.materials.RMDHOHZakhhXXHT} />
      <T.Mesh geometry={gltf.nodes.ebZHPVwKTmqvgbU.geometry} material={gltf.materials.kDpbvvjwMgCSCmF} />
      <T.Mesh geometry={gltf.nodes.uSnVzUkbvcGaVtm.geometry} material={gltf.materials.AqVxlXuHIFahLKs} />
      <T.Mesh geometry={gltf.nodes.znOBoeqnOAcWvld.geometry} material={gltf.materials.dKLyhhkbEyMrqky} />
      <T.Mesh geometry={gltf.nodes.tIZmzvOOHrlOFci.geometry} material={gltf.materials.oKQWdLrXUCbYByI} />
      <T.Mesh geometry={gltf.nodes.UmfOhraHkqkMHJr.geometry} material={gltf.materials.OFvWomWIIUgmKKA} />
      <T.Mesh geometry={gltf.nodes.roXkINNmErodbSy.geometry} material={gltf.materials.oKQWdLrXUCbYByI} />
      <T.Mesh geometry={gltf.nodes.wWWhLQmmNVhThGV.geometry} material={gltf.materials.OFvWomWIIUgmKKA} />
      <T.Mesh geometry={gltf.nodes.JoRHkRchuIHZFdI.geometry} material={gltf.materials.mEMAJQfiigHeUXV} />
      <T.Mesh geometry={gltf.nodes.qJLFXXZhlqhKvcM.geometry} material={gltf.materials.mEMAJQfiigHeUXV} />
      <T.Mesh geometry={gltf.nodes.thJvyyEdPZIkQGr.geometry} material={gltf.materials.OFvWomWIIUgmKKA} />
      <T.Mesh geometry={gltf.nodes.juMIjHdkYweLlGP.geometry} material={gltf.materials.NzmRSNqyvNKhkmK} />
      <T.Mesh geometry={gltf.nodes.zNYAavJLMZZchIX.geometry} material={gltf.materials.ASadxrcBIAXFnLn} />
      <T.Mesh geometry={gltf.nodes.bzbXKgxvWZbXAqu.geometry} material={gltf.materials.JKvAHnqjqlqshmY} />
      <T.Mesh geometry={gltf.nodes.guzkNjLPdYYIFbm.geometry} material={gltf.materials.dkOmcmuFedorUKC} />
      <T.Mesh geometry={gltf.nodes.CkZgGMshUOhytMM.geometry} material={gltf.materials.AvocVUvikCzzMtu} />
      <T.Mesh geometry={gltf.nodes.oiLbjgjnUUhPosp.geometry} material={gltf.materials.AvocVUvikCzzMtu} />
      <T.Mesh geometry={gltf.nodes.nDWhlgWONddUcnN.geometry} material={gltf.materials.wOIDWopwzKBeTNU} />
      <T.Mesh geometry={gltf.nodes.VAcTKRVsYcEMWxB.geometry} material={gltf.materials.dkOmcmuFedorUKC} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
